### PR TITLE
fix: check Token Amount and Disable the button

### LINKED ISSUE #136: Fix unfunded wallet deposits
Right now an unfunded wallet is able to deposit, receiving a transaction error. We need to prevent the deposit launch 

image

### PR DESCRIPTION
**Pull request by Shikhar15606**
check Token Amount and Disable the button

fix #136

### CODE REVIEW

**Comment by Shikhar15606** [comment]
Hi @thegreat-vanderlinde There is still one issue in this PR: The tooltip with the message "Not enough tokens" is not working as I expect. I looked at the evergreen UI docs: https://evergreen.segment.com/components/tooltip#conditionally_show_tooltip
and set the isShown to undefined, when we do not have enough tokens, but still, the tooltip is not appearing.

File: src/components/organisms/actionButtons/DepositButton.tsx [hunk 1]
```diff
@@ -17,6 +18,17 @@ const DepositButton = ({ otcStatePubkey, isBuyer }: { otcStatePubkey: string; is
 	const provider = new AnchorProvider(connection, wallet, {});
 	const rateStateQuery = useGetFetchOTCStateQuery(connection, otcStatePubkey);
 	const [isLoading, setIsLoading] = useState(false);
+	const [isButtonDisabled, setIsButtonDisabled] = useState(false);
+
+	const checkTokenAmountHelper = useCallback(async()=>{
+		const res = await checkTokenAmount(connection, wallet.publicKey, new PublicKey('7XSvJnS19TodrQJSbjUR6tEGwmYyL1i9FX7Z5ZQHc53W'), isBuyer ? rateStateQuery.data.buyerDepositAmount : rateStateQuery.data.sellerDepositAmount);
+		console.log(res);
+		setIsButtonDisabled(!res);
+	}, [connection, wallet.publicKey, isBuyer, rateStateQuery.data.buyerDepositAmount, rateStateQuery.data.sellerDepositAmount]);
```
Comment (thegreat-vanderlinde) [inline src/components/organisms/actionButtons/DepositButton.tsx:27]: the amount needed can be moved outside the checK:
```ts
const amountNeeded = isBuyer ? rateStateQuery.data.buyerDepositAmount : rateStateQuery.data.sellerDepositAmount
```
so the method (and the dependencies) will be lighter

File: src/components/organisms/actionButtons/DepositButton.tsx [hunk 2]
```diff
@@ -17,6 +18,17 @@ const DepositButton = ({ otcStatePubkey, isBuyer }: { otcStatePubkey: string; is
 	const provider = new AnchorProvider(connection, wallet, {});
 	const rateStateQuery = useGetFetchOTCStateQuery(connection, otcStatePubkey);
 	const [isLoading, setIsLoading] = useState(false);
+	const [isButtonDisabled, setIsButtonDisabled] = useState(false);
+
+	const checkTokenAmountHelper = useCallback(async()=>{
+		const res = await checkTokenAmount(connection, wallet.publicKey, new PublicKey('7XSvJnS19TodrQJSbjUR6tEGwmYyL1i9FX7Z5ZQHc53W'), isBuyer ? rateStateQuery.data.buyerDepositAmount : rateStateQuery.data.sellerDepositAmount);
```
Comment (thegreat-vanderlinde) [inline src/components/organisms/actionButtons/DepositButton.tsx:24]: we cannot hard code the mint needed here. it's available in otcState object

File: src/components/atoms/ButtonPill/ButtonPill.tsx [hunk 3]
```diff
@@ -9,19 +9,23 @@ type ButtonPillProps = {
...
+				className={cn(styles.button, styles[mode], loading && styles.disabled)}
+				onClick={onClick}
+				appearance="primary"
+				iconBefore={icon}
+				isLoading={loading}
+				disabled={disabled}
+			>
+				{text}
+			</Button>
+		</Tooltip>
```
Comment (thegreat-vanderlinde) [inline src/components/atoms/ButtonPill/ButtonPill.tsx:28]: the ButtonPill component it's a reusable component, we can't hardcode a logic so specific like `if disable show "not enough tokens"`. This will make the component hardly reusable in the future.

Please leave this logic in the parent component.

**Review by thegreat-vanderlinde — CHANGES_REQUESTED** [review]

**Comment by Shikhar15606** [comment]
Hi, @thegreat-vanderlinde I just pushed the requested changes. The tooltip is still not working :pensive:

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde PTAL

File: src/utils/solanaHelper.ts [hunk 4]
```diff
@@ -8,3 +9,16 @@ export async function accountExists(c: Connection, a: PublicKey): Promise<boolea
...
+		const atoken = await getAssociatedTokenAddress(mintPubKey, payerPubKey);
+		const accountInfo = await getAccount(connection, atoken);
+		const mintInfo = await getMint(connection, mintPubKey);
+		if(accountInfo.amount / BigInt(10 ** mintInfo.decimals) >= requiredAmount) return true;
+		else return false;
+	} catch (err) {
+		// token account not found
+		return false;
+	}
+}
```
[the remark this answers is not in the document]
Comment (Shikhar15606) [reply src/utils/solanaHelper.ts]: Ya, I fixed that

File: src/components/organisms/actionButtons/DepositButton.tsx (hunk 1 above)
Comment (Shikhar15606) [reply src/components/organisms/actionButtons/DepositButton.tsx]: Ya sure, I fixed that

File: src/components/atoms/ButtonPill/ButtonPill.tsx (hunk 3 above)
Comment (Shikhar15606) [reply src/components/atoms/ButtonPill/ButtonPill.tsx]: Ya sure, I fixed that

**Comment by Shikhar15606** [comment]
Resolved the merge conflicts

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde I just resolved the merge conflicts

**Review by thegreat-vanderlinde — APPROVED** [review]
lgtm
