### PR TITLE
fix(_document.tsx): fixed Flickering UI

### LINKED ISSUE #78: Fix icons flickering on refresh
During a refresh we have a super short flickering with all icons in the page, see attached video.

https://user-images.githubusercontent.com/91868385/193415556-8226b4d0-3793-4b81-8d69-fd830f368404.mov

### PR DESCRIPTION
**Pull request by Shikhar15606**
The change fixes the flickering problem for all the pages. It extracts the evergreen styles and adds them to the HTML of the web page

fix #78

### CODE REVIEW

File: src/pages/_document.tsx [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import { extractStyles } from 'evergreen-ui';
+import Document, { Html, Head, Main, NextScript } from 'next/document';
+
+export default class MyDocument extends Document<{css: any, hydrationScript:any}> {
```
Comment (GnosisAssembler) [inline src/pages/_document.tsx:4]: A small detail. Can we change the name to a more meaningful one? Like `NextDocument` for example.

**Review by GnosisAssembler — CHANGES_REQUESTED** [review]
Looks really good. Very good job, figuring out how to use the `hydrationScript` from `evergreen`, with `Next.js`.

File: src/pages/_document.tsx (hunk 1 above)
Comment (Shikhar15606) [reply src/pages/_document.tsx:4]: Ya Sure, ```NextDocument``` seems good.

**Review by GnosisAssembler — APPROVED** [review]

**Review by thegreat-vanderlinde — APPROVED** [review]
