### PR TITLE
fix(topbar.tsx): topBar UI Fixes

### LINKED ISSUE #120: Keep track of the active tab in the navbar menu
Create a utility function to keep track of the **active** tab in the navbar menu (TopBar).

The active tab, should have **darker** color, when hovered or active.

Also fix the styling issue with the `font-weight`, in the **home** item.

fix

### PR DESCRIPTION
**Pull request by Shikhar15606**
tracking the active tab in the navbar menu along with a few bug fixes

fix #120

### CODE REVIEW

File: src/components/organisms/TopBar/TopBar.tsx [hunk 1]
```diff
@@ -46,7 +50,7 @@ const TopBar = () => {
 					</div>
 
 					{/* CREATE CONTRACT LINK */}
-					<div className={cn(styles.item)}>
+					<div className={activeNavItem === 1 ? cn(styles.item, styles.active) : cn(styles.item)} onClick={()=> setActiveNavItem(1)}>
```
Comment (thegreat-vanderlinde) [inline src/components/organisms/TopBar/TopBar.tsx:53]: we should listen on URL changes instead of setting the active route programmatically, we can have multiple ways to change routes apart from the TopBar links.

**Review by thegreat-vanderlinde — CHANGES_REQUESTED** [review]
this is not working as intended

https://user-images.githubusercontent.com/91868385/194565291-396181ce-3241-4e83-a68f-6276ed1fc7ad.mov

**Review by thegreat-vanderlinde — APPROVED** [review]
lgtm

**Comment by thegreat-vanderlinde** [comment]
@Shikhar15606 now PR looks fine, can you please fix conflicts?

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde Conflicts Resolved

**Comment by Shikhar15606** [comment]
Let me add the explorer page in the navbar as well

**Comment by Shikhar15606** [comment]
Ya, sure

**Review by thegreat-vanderlinde — APPROVED** [review]
