### PR TITLE
249 - hide the claim button after token transfer

### LINKED ISSUE #249: Claimed twice after settlement
**Describe the bug**
After settling the [following contract](3tmR65f7sULhZdjM2fw9XAFmPdfj7MwTygWhiFaEvdQj) I was able to call "Claim" twice.

First claim I redeemed the right amount (https://solscan.io/tx/5xvReEepzqamD2w87nCPUUfdXU5XnHqQqTCTUBApSg4dHG2hAF6jCkzKezvLxaZLLoRrZdMSQyAPh97uwukPYjgx)

Second claim I redeemed zero (https://solscan.io/tx/34phi5zC7RvmoodUrSdb5mrNuBunB7GXkMFppxZdMPEgzqojGM7iy8QxSQpuQok2EB5VK3vNymc5W2Q3rgHcMxMm)

**Expected behavior**
No second claim should be possible.

### PR DESCRIPTION
**Pull request by Shikhar15606**
Added a listener to listen for token transfer and hide the claim button as soon as the transfer is completed.

fix #249

### CODE REVIEW

File: src/components/organisms/actionButtons/ClaimButton.tsx [hunk 1]
```diff
@@ -17,6 +21,38 @@ const ClaimButton = ({ otcStatePubkey, isBuyer }: { otcStatePubkey: string; isBu
...
+	const [isDeposited, setIsDeposited] = useState(false);
+
+	const getProgramTokenAccount = useCallback(async ()=>{
+		const vyperOtcProgram = new Program<VyperOtc>(VyperOtcIDL, new PublicKey(PROGRAMS.VYPER_OTC_PROGRAM_ID), new AnchorProvider(connection, undefined, {}));
+		const accountInfo = await vyperOtcProgram.account.otcState.fetch(otcStatePubkey);
+		if(isBuyer) {
+			return accountInfo.otcSeniorReserveTokenAccount;
+		}else{
+			return accountInfo.otcJuniorReserveTokenAccount;
+		}
```
Comment (thegreat-vanderlinde) [inline src/components/organisms/actionButtons/ClaimButton.tsx:33]: let's add these account in the ChainOtcState class as suggested on discord

**Review by thegreat-vanderlinde — CHANGES_REQUESTED** [review]

**Comment by Shikhar15606** [comment]
@thegreat-vanderlinde I just refactored the code as suggested above. PTAL

**Review by thegreat-vanderlinde — APPROVED** [review]
